# Generated by Django 3.2.2 on 2021-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
