# Generated by Django 3.2.2 on 2021-05-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='extra_details',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
