# Generated by Django 3.2.2 on 2021-05-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artist_extra_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='extra_details',
        ),
    ]
